server {

    listen 80;  # Listen on port 80 (HTTP)
    server_name localhost;  # Accept requests for any hostname (change to your domain in production)
    server_tokens off;  # Hide Nginx version in error pages and headers for security

    client_max_body_size 20M;  # Limit the maximum client request body size (e.g., file uploads)

     # Handle requests to the root URL
    location / {
        try_files $uri @proxy_api;  # Try serving a static file, else forward the request to @proxy_api
    }

    # Handle requests to the Django admin panel
    location /admin {
        try_files $uri @proxy_api;  # Try serving a static file, else forward the request to @proxy_api
    }
    #--------------------------------------------------------------------------------------------------------------------------------------------->
    # The server will formard all / and /admin requests to the @proxy_api, which is our gunicorn serving Django.
    # The /django_static/ requests will be served from /app/backend/django_static/ - it is a path where static files will be collected by Django
    #_____________________________________________________________________________________________________________________________________________/

    # Proxy all unmatched requests to the Django backend running on port 8000
    location @proxy_api {
        proxy_set_header Host $http_host;  # Preserve the original Host header
        proxy_redirect off;  # Prevent automatic redirection by Nginx
        proxy_pass  http://planetarium-backend:8000;  # Forward the request to the Django application running on port 8000
    }

    # Serve static files collected by Django
    location /django_static/ {
        autoindex on;  # Enable directory listing (consider disabling in production)
        alias /app/backend/django_static/;  # Path where Django collects static files
        expires 30d;  # Cache static files for 30 days
        add_header Cache-Control "public, max-age=2592000";  # Set cache headers
    }

    # Serve media files uploaded by users
    location /media/ {
        autoindex on;  # Enable directory listing (consider disabling in production)
        alias /app/backend/media/;  # Path where Django stores uploaded media files
        expires 30d;  # Cache media files for 30 days
        add_header Cache-Control "public, max-age=2592000";  # Set cache headers
    }
}
